services:
  github-api:
    environment:
      GITHUB_TOKEN: (set in compose.override.yaml)
    image: ghcr.io/williamjacksn/github-api
    init: true
    volumes:
      - ./:/app

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/github-api
    init: true
    volumes:
      - ./:/app
