services:
  github-api:
    environment:
      GITHUB_TOKEN: (set in compose.override.yaml)
    image: ghcr.io/williamjacksn/github-api
    init: true
    volumes:
      - ./:/home/python/github-api
    working_dir: /home/python/github-api

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/github-api
    init: true
    volumes:
      - ./:/home/python/github-api
    working_dir: /home/python/github-api
