version: '3.8'

services:
  repository-watching:
    image: docker.pkg.github.com/williamjacksn/github-api/github-api
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command:
      - repository-watching.py
